name: Deploy main branch

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run tsc

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run lint

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run test:unit

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run test:integration

  deploy:
    needs: [tsc, lint, unit-tests, integration-tests]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - name: serverless deploy
        run: npm run prod:deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

#  publish-types:
#    needs: [deploy]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: '22'
#      - run: npm ci
#      - run: npm run build
#      - name: Configure npm auth
#        env:
#          TOKEN: ${{ secrets.MY_FLOWERS_NPM_PUBLISH_TOKEN }}
#        run: |
#          echo "Token suffix: ${TOKEN: -3}"
#          npm config set //npm.pkg.github.com/:_authToken $TOKEN
#      - name: Debug npm config
#        run: |
#          npm config list
#          cat ~/.npmrc
#      - run: npm publish
